In [1]:
import sys
import os
sys.path.append(os.path.abspath('..'))

import data_gen as dg
import ising as isg

import jax
import jax.numpy as jnp
import optax

In [ ]:
d = 5

n_init = 100

n_replicas = 500

h, J = dg.generate_ising_params(d, sigma_h=1, sigma_J=0.5, seed=0)

In [10]:
samples = dg.generate_ising_data(n_init, n_replicas, h=h, J=J, n_steps_equil=10000, n_steps_final=5000, n_prints = 5000, beta=1, seed=12)

step 0:[-0.18000000715255737, 0.06000000238418579, -0.14000000059604645, -0.18000000715255737, 0.08000000566244125]
[-0.08000000566244125, 0.38700002431869507, 0.07300000637769699, -0.18700000643730164, 0.17000000178813934]
0.1446000039577484

step 5000:[0.36000001430511475, -0.3800000250339508, -0.36000001430511475, 0.320000022649765, -0.4000000059604645]
[0.7990000247955322, -0.9300000667572021, -0.5610000491142273, 0.6360000371932983, -0.8080000281333923]
0.08080001920461655

step 10000:[0.06000000238418579, -0.06000000238418579, -0.04000000283122063, 0.04000000283122063, -0.08000000566244125]
[0.26600000262260437, -0.3230000138282776, -0.16500000655651093, 0.023000001907348633, -0.23500001430511475]
0.07080000638961792



In [11]:
import numpy as np

unique = []
counts = []

for i in range(len(samples)):
    found = False
    for j in range(len(unique)):
        if np.array_equal(samples[i], unique[j]):
            counts[j] += 1
            found = True
            break
    if not found:
        unique.append(samples[i])
        counts.append(1)

In [12]:
for i in range(len(unique)):
    print(unique[i], counts[i])

[-1  1  1 -1  1] 17884
[ 1 -1 -1  1 -1] 28581
[-1  1 -1 -1  1] 1059
[ 1 -1 -1 -1 -1] 400
[ 1 -1  1  1 -1] 1160
[-1  1  1 -1 -1] 93
[ 1  1  1 -1  1] 147
[-1 -1 -1 -1  1] 4
[ 1 -1 -1  1  1] 95
[ 1 -1  1 -1 -1] 79
[-1  1 -1 -1 -1] 26
[ 1 -1  1  1  1] 16
[-1  1  1  1  1] 147
[-1 -1 -1  1 -1] 144
[-1 -1 -1  1  1] 17
[-1 -1  1  1  1] 8
[ 1 -1  1 -1  1] 20
[ 1  1  1 -1 -1] 17
[-1  1 -1  1  1] 53
[ 1  1  1  1 -1] 2
[ 1  1 -1 -1  1] 9
[ 1 -1 -1 -1  1] 11
[ 1  1 -1 -1 -1] 5
[-1  1 -1  1 -1] 6
[-1 -1 -1 -1 -1] 1
[-1 -1  1 -1  1] 3
[-1 -1  1  1 -1] 5
[-1  1  1  1 -1] 4
[1 1 1 1 1] 3
[ 1  1 -1  1 -1] 1
