In [1]:
import sys
import os
sys.path.append(os.path.abspath('..'))

import data_gen as dg
import ising as isg

import jax
import jax.numpy as jnp
import optax

In [8]:
d = 5

n_init = 10

n_replicas = 5

h, J = dg.generate_ising_params(d, sigma_h=0.1, sigma_J=0.1, mean_h=0, mean_J=0, seed=0)

In [23]:
samples = dg.generate_ising_data(
    n_init=n_init,
    n_replicas = n_replicas,
    h=h,
    J=J,
    n_steps_equil=10000,
    n_steps_final=500,
    n_prints=5000,
    beta=2.0,
    seed=123
)

step 0:[-0.4000000059604645, -0.20000000298023224, -0.20000000298023224, 0.4000000059604645, 0.4000000059604645]
[0.18400001525878906, -0.030000001192092896, -0.18800000846385956, -0.1980000138282776, -0.22300000488758087]
0.0910000130534172

step 5000:[0.4000000059604645, -0.4000000059604645, -0.20000000298023224, 0.4000000059604645, -0.20000000298023224]
[0.492000013589859, -0.6420000195503235, -0.33900001645088196, 0.05100000277161598, -0.5360000133514404]
0.19480000436306

step 10000:[0.4000000059604645, 0.0, -0.6000000238418579, -0.20000000298023224, -0.6000000238418579]
[0.3960000276565552, -0.609000027179718, -0.22700001299381256, 0.009000000543892384, -0.37400001287460327]
0.039000000804662704



In [24]:
import numpy as np

unique = []
counts = []

for i in range(len(samples)):
    found = False
    for j in range(len(unique)):
        if np.array_equal(samples[i], unique[j]):
            counts[j] += 1
            found = True
            break
    if not found:
        unique.append(samples[i])
        counts.append(1)

In [25]:
for i in range(len(unique)):
    print(unique[i], counts[i])

[ 1 -1  1 -1 -1] 2
[ 1 -1 -1  1 -1] 18
[ 1  1  1 -1 -1] 1
[-1 -1 -1  1 -1] 3
[ 1 -1  1  1  1] 1
[-1  1  1 -1  1] 4
[ 1 -1 -1 -1 -1] 6
[-1 -1 -1  1  1] 1
[-1  1  1 -1 -1] 2
[1 1 1 1 1] 1
[-1 -1 -1 -1  1] 1
[-1  1 -1 -1  1] 3
[ 1 -1  1  1 -1] 4
[ 1 -1 -1  1  1] 1
[-1 -1  1  1 -1] 1
[ 1 -1 -1 -1  1] 1


In [18]:
h

Array([ 0.10040142, -0.09063372, -0.07481723, -0.11713669, -0.08712328],      dtype=float32)

In [19]:
J

Array([[ 0.        , -0.32142323,  0.00159719,  0.00892405, -0.18679683],
       [-0.32142323,  0.        ,  0.1261178 , -0.25008357,  0.18081972],
       [ 0.00159719,  0.1261178 ,  0.        , -0.08179495,  0.09573315],
       [ 0.00892405, -0.25008357, -0.08179495,  0.        , -0.1146527 ],
       [-0.18679683,  0.18081972,  0.09573315, -0.1146527 ,  0.        ]],      dtype=float32)